version: '3.7'
services:
  app:
    build: .
    container_name: product-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - database
  database:
    container_name: postgres_product-db
    image: postgres:12
    environment:
      POSTGRES_USER: product-db
      POSTGRES_PASSWORD: product-db
    ports:
      - "5432:5432"